# Generated by Django 5.2.1 on 2025-05-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.TextField()),
                ('sex', models.CharField(choices=[('FM', 'Female'), ('ML', 'Male')], max_length=2)),
            ],
        ),
    ]
