# Generated by Django 5.2.1 on 2025-05-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0002_author_book_bookinstance_genre_delete_trainer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back']},
        ),
    ]
