# Generated by Django 5.2.1 on 2025-05-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0004_bookinstance_borrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
